baseurl = "https://zhmp.net"
theme = "dimension"
languageCode = "en-us"

[params]
  title = "Anthony Cast"
  author = "Anthony Cast"
  description = "analyst boardgamer cyclist director explorer father humanist intj leader partner pragmatist reader runner skeptic"
  logo = "fa-rocket"
  copyright = "2019"
  staticDir = "static"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/anthonycast"

[[params.social]]
  medium = "mastodon"
  icon = "paper-plane"
  link = "https://mstdn.io/@anonyth"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/anthony.cast"

[[params.social]]
  medium = "google"
  icon = "google-plus"
  link = "https://plus.google.com/107910329408288699054"

[[params.social]]
  medium = "pinterest"
  icon = "pinterest"
  link = "https://www.pinterest.com/anthonycast/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/anonyth"

[[params.social]]
  medium = "keybase"
  icon = "key"
  link = "https://keybase.io/anonyth"

[[params.social]]
  medium = "drupal"
  icon = "drupal"
  link = "https://www.drupal.org/u/anonyth"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/anthonycast/"

[[params.social]]
  medium = "angellist"
  icon = "angellist"
  link = "https://angel.co/anthony-cast"

[[params.social]]
  medium = "remote"
  icon = "briefcase"
  link = "https://remote.com/anthonycast"

[[params.social]]
  medium = "lastfm"
  icon = "lastfm"
  link = "https://www.last.fm/user/designori"

[[params.social]]
  medium = "bandcamp"
  icon = "bandcamp"
  link = "https://bandcamp.com/anonyth"

[[params.social]]
  medium = "pinboard"
  icon = "bookmark-o"
  link = "https://pinboard.in/u:voigtkampff"

[[params.social]]
  medium = "boardgamegeek"
  icon = "cubes"
  link = "https://www.boardgamegeek.com/user/voigtkampff"

[[params.social]]
  medium = "yucata"
  icon = "user-o"
  link = "https://www.yucata.de/en/user/anonyth"

[[params.social]]
  medium = "instapaper"
  icon = "newspaper-o"
  link = "https://www.instapaper.com/p/anthonycast"

[[params.social]]
  medium = "pocket"
  icon = "get-pocket"
  link = "https://getpocket.com/@anonyth"
  
[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/@anthonycast"

[[params.social]]
  medium = "goodreads"
  icon = "book"
  link = "https://goodreads.com/anonyth"

[[params.social]]
  medium = "tumblr"
  icon = "tumblr"
  link = "http://anonyth.tumblr.com/"

[[params.social]]
  medium = "quora"
  icon = "quora"
  link = "https://www.quora.com/profile/anthony-cast"

[[params.social]]
  medium = "geocaching"
  icon = "map-o"
  link = "https://www.geocaching.com/p/default.aspx?guid=ccf42981-c2cb-4bf2-983b-cd361fd9d011"

[[params.social]]
  medium = "meetup"
  icon = "meetup"
  link = "https://www.meetup.com/members/352189/"

[[params.social]]
  medium = "telegram"
  icon = "telegram"
  link = "https://t.me/anthonycast"
